export const questionData = [
  {
    id: 401,
    title: "Binary Watch",
    acceptance: "55.1%",
    difficulty: "Easy",
    status: "open",
    solution: "solution-url",
  },
  {
    id: 402,
    title: "Remove K Digits",
    acceptance: "33.9%",
    difficulty: "Medium",
    status: "locked",
    solution: "",
  },
  {
    id: 403,
    title: "Frog Jump",
    acceptance: "46.2%",
    difficulty: "Hard",
    status: "open",
    solution: "solution-url",
  },
  {
    id: 404,
    title: "Sum of Left Leaves",
    acceptance: "60.9%",
    difficulty: "Easy",
    status: "open",
    solution: "solution-url",
  },
  {
    id: 405,
    title: "Convert a Number to Hexadecimal",
    acceptance: "49.2%",
    difficulty: "Easy",
    status: "open",
    solution: "solution-url",
  },
  {
    id: 406,
    title: "Queue Reconstruction by Height",
    acceptance: "73.7%",
    difficulty: "Medium",
    status: "open",
    solution: "solution-url",
  },
  {
    id: 407,
    title: "Trapping Rain Water II",
    acceptance: "48.2%",
    difficulty: "Hard",
    status: "open",
    solution: "solution-url",
  },
  {
    id: 408,
    title: "Valid Word Abbreviation",
    acceptance: "36.1%",
    difficulty: "Easy",
    status: "open",
    solution: "solution-url",
  },
  {
    id: 409,
    title: "Longest Palindrome",
    acceptance: "55.4%",
    difficulty: "Easy",
    status: "open",
    solution: "solution-url",
  },
  {
    id: 410,
    title: "Split Array Largest Sum",
    acceptance: "56.3%",
    difficulty: "Hard",
    status: "open",
    solution: "solution-url",
  },
  {
    id: 411,
    title: "Minimum Unique Word Abbreviation",
    acceptance: "39.8%",
    difficulty: "Hard",
    status: "open",
    solution: "solution-url",
  },
  {
    id: 412,
    title: "Fizz Buzz",
    acceptance: "72.9%",
    difficulty: "Easy",
    status: "open",
    solution: "solution-url",
  },
  {
    id: 413,
    title: "Arithmetic Slices",
    acceptance: "65.0%",
    difficulty: "Medium",
    status: "open",
    solution: "solution-url",
  },
  {
    id: 414,
    title: "Third Maximum Number",
    acceptance: "35.5%",
    difficulty: "Easy",
    status: "open",
    solution: "solution-url",
  },
  {
    id: 415,
    title: "Add Strings",
    acceptance: "51.6%",
    difficulty: "Easy",
    status: "open",
    solution: "solution-url",
  },
  {
    id: 416,
    title: "Partition Equal Subset Sum",
    acceptance: "46.7%",
    difficulty: "Medium",
    status: "open",
    solution: "solution-url",
  },
  {
    id: 417,
    title: "Pacific Atlantic Water Flow",
    acceptance: "55.9%",
    difficulty: "Medium",
    status: "open",
    solution: "solution-url",
  },
  {
    id: 418,
    title: "Sentence Screen Fitting",
    acceptance: "36.3%",
    difficulty: "Medium",
    status: "open",
    solution: "solution-url",
  },
  {
    id: 419,
    title: "Battleships in a Board",
    acceptance: "75.6%",
    difficulty: "Medium",
    status: "open",
    solution: "solution-url",
  },
  {
    id: 420,
    title: "Strong Password Checker",
    acceptance: "14.0%",
    difficulty: "Hard",
    status: "open",
    solution: "solution-url",
  },
  {
    id: 421,
    title: "Maximum XOR of Two Numbers in an Array",
    acceptance: "53.3%",
    difficulty: "Medium",
    status: "open",
    solution: "solution-url",
  },
  {
    id: 422,
    title: "Valid Word Square",
    acceptance: "41.4%",
    difficulty: "Easy",
    status: "open",
    solution: "solution-url",
  },
  {
    id: 423,
    title: "Reconstruct Original Digits from English",
    acceptance: "51.2%",
    difficulty: "Medium",
    status: "open",
    solution: "solution-url",
  },
  {
    id: 424,
    title: "Longest Repeating Character Replacement",
    acceptance: "55.1%",
    difficulty: "Medium",
    status: "open",
    solution: "solution-url",
  },
  {
    id: 425,
    title: "Word Squares",
    acceptance: "53.5%",
    difficulty: "Hard",
    status: "open",
    solution: "solution-url",
  },
  {
    id: 426,
    title: "Convert Binary Search Tree to Sorted Doubly Linked List",
    acceptance: "64.9%",
    difficulty: "Medium",
    status: "open",
    solution: "solution-url",
  },
  {
    id: 427,
    title: "Construct Quad Tree",
    acceptance: "75.9%",
    difficulty: "Medium",
    status: "open",
    solution: "solution-url",
  },
  {
    id: 428,
    title: "Serialize and Deserialize N-ary Tree",
    acceptance: "67.5%",
    difficulty: "Hard",
    status: "open",
    solution: "solution-url",
  },
  {
    id: 429,
    title: "N-ary Tree Level Order Traversal",
    acceptance: "71.0%",
    difficulty: "Medium",
    status: "open",
    solution: "solution-url",
  },
  {
    id: 430,
    title: "Flatten a Multilevel Doubly Linked List",
    acceptance: "60.4%",
    difficulty: "Medium",
    status: "open",
    solution: "solution-url",
  },
  {
    id: 431,
    title: "Encode N-ary Tree to Binary Tree",
    acceptance: "79.7%",
    difficulty: "Hard",
    status: "open",
    solution: "solution-url",
  },
  {
    id: 432,
    title: "All O`one Data Structure",
    acceptance: "37.1%",
    difficulty: "Hard",
    status: "open",
    solution: "solution-url",
  },
  {
    id: 433,
    title: "Minimum Genetic Mutation",
    acceptance: "54.3%",
    difficulty: "Medium",
    status: "open",
    solution: "solution-url",
  },
  {
    id: 434,
    title: "Number of Segments in a String",
    acceptance: "36.4%",
    difficulty: "Easy",
    status: "open",
    solution: "solution-url",
  },
  {
    id: 435,
    title: "Non-overlapping Intervals",
    acceptance: "54.0%",
    difficulty: "Medium",
    status: "open",
    solution: "solution-url",
  },
  {
    id: 436,
    title: "Find Right Interval",
    acceptance: "52.6%",
    difficulty: "Medium",
    status: "open",
    solution: "solution-url",
  },
  {
    id: 437,
    title: "Path Sum III",
    acceptance: "46.1%",
    difficulty: "Medium",
    status: "open",
    solution: "solution-url",
  },
  {
    id: 438,
    title: "Find All Anagrams in a String",
    acceptance: "51.2%",
    difficulty: "Medium",
    status: "open",
    solution: "solution-url",
  },
];
